#!/bin/bash
# Build the article

rm *.aux
rm *.bbl
pdflatex -shell-escape Sunpy_paper_0.4.tex
pdflatex -shell-escape Sunpy_paper_0.4.tex
bibtex Sunpy_paper_0.4
pdflatex -shell-escape Sunpy_paper_0.4.tex
pdflatex -shell-escape Sunpy_paper_0.4.tex
